{{- if eq "alb" .Values.loadbalancer }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: memphis{{ .Values.environment }}
  name: memphis-ui-alb
  annotations:
    {{- if .Values.externalType }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    {{- end }}
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    {{- if .Values.enablessl }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificatearn }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    {{- end }}
spec:
  rules:
    - http:
        paths:
        - backend:
            service:
              name: memphis-cluster
              port:
                number: {{ .Values.memphis.uiport }}
          path: /
          pathType: Prefix
      {{- if .Values.hostname }}
      host: {{ .Values.hostname }}
      {{- end }}
{{- end }}