{{- if eq "nlb" .Values.loadbalancer }}
apiVersion: v1
kind: Service
metadata:
  name: memphis-ui-nlb
  namespace: memphis{{ .Values.environment }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    {{- if .Values.externalType }}
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    {{- end }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.memphis.ui-port }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: memphis
  type: LoadBalancer
{{- end }}