apiVersion: v1
kind: Service
metadata:
  name: memphis-sdk-nlb
  namespace: memphis{{ .Values.environment }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    {{- if .Values.externalType }}
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    {{- end }}
    {{- if .Values.hostnamesdk }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostnamesdk }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.memphis.sdkport }}
    protocol: TCP
    targetPort: {{ .Values.memphis.sdkport }}
  selector:
    app.kubernetes.io/name: memphis
  type: LoadBalancer